### ISSUE TITLE
How can I separate the reduced dataset into images derived from LSUN and Stanford car?

### ISSUE THREAD

**Issue by yulonglin** [Tin-Kramberger/LSUN-Stanford-dataset#4]
How can we extract images in the LSUN-Stanford that were derived from LSUN car and Stanford car separately? I am trying to separate them so one of there are two slightly different distributions, one for training and one for testing.

From the `.sql` file, in the `image` table I see files like `5b55df4805184ad24a7eb281e5836109d0d060.webp` which I guess aren't from the Stanford car since there are already `cars_train` and `cars_test` entries in the `image` table. Where do they come from? The StyleGAN team extracted `.png` images directly in the recent papers (e.g. ADA) and I'm guessing for StyleGAN too?

**Comment by Tin-Kramberger** [comment]
All LSUN images are in webp format after extraction from their database. That's the default behaviour, as you can see in https://github.com/fyu/lsun/blob/master/data.py

If you want to seperate them, I would suggest to write your own SQL query which you would filter out LSUN and Stanford images by their file extensions. Eg. "select * from images where filename like '%.webp';". 
It would take some time, but it would get the job done. Or add a boolean or bit column within the table to later on more easily filter out the results.  
All the images are feed into the StyleGAN script for data preparation which converts them into another format as you can see here: https://github.com/NVlabs/stylegan/blob/master/dataset_tool.py
I do not know how StyleGAN 2 handles data preparation, but my guess is the same because the same tools are present: https://github.com/NVlabs/stylegan2/blob/master/dataset_tool.py

cars_train and cars_test are original folder names of the Stanford car dataset which is already separated into two dataset used for training and testing.
